'''
Another Pi
Generated by Google Gemini Pro
https://googlegemini.co/try-google-gemini-for-free
这个程序的运行结果是错误的
'''

import decimal
import math

def calculate_pi(n):
  """Calculates pi to n decimal places using the Machin-like formula.

  Args:
    n: The number of decimal places to calculate.

  Returns:
    A string representing pi to n decimal places.
  """

  # Set the precision of the decimal module.
  decimal.getcontext().prec = n + 20

  # Initialize the variables.
  k = 0
  a = decimal.Decimal(1)
  b = decimal.Decimal(24)
  c = decimal.Decimal(1)

  # Calculate pi using the Machin-like formula.
  while k < n:
    a_temp = a
    a = a + b * c
    b = decimal.Decimal(1) / (a_temp + b)
    c = 2 - c
    k += 8

  # Return pi as a string.
  return str(a)[:n]

def main():
  # Get the number of decimal places from the user.
  n = int(input("Enter the number of decimal places to calculate: "))

  # Calculate pi.
  pi = calculate_pi(n)

  # Print pi.
  print("Pi to", n, "decimal places is:", pi)

if __name__ == "__main__":
  main()