'''
Generated by Google Gemini Pro
https://googlegemini.co/try-google-gemini-for-free
不收敛或收敛太慢，运行时间过长
'''

from decimal import *
import math

def pi(n):
    """
    Calculate pi to n decimal places.

    Args:
        n: The number of decimal places to calculate.

    Returns:
        A string representing pi to n decimal places.
    """

    # Set the precision to n + 1 decimal places. This ensures that the
    # result is rounded to the correct number of decimal places.
    getcontext().prec = n + 1

    # Calculate pi using the Gauss-Legendre algorithm.
    pi = 0
    k = 0
    while True:
        # Calculate the next term in the series.
        term = (-1)**k * Decimal(math.factorial(4 * k)) / (Decimal(2 * k + 1) * Decimal(math.factorial(k)**2))
        print("k={}，  term={}".format(k,term))  # 我加的调试输出信息

        # Add the term to the sum.
        pi += term

        # If the term is less than 1e-15, then the sum has converged.
        if abs(term) < 1e-15:
            break

        # Increment the counter.
        k += 1

    # Round the result to n decimal places.
    return str(pi.quantize(Decimal('1e-%d' % n)))

# Print the value of pi to 100 decimal places.
print(pi(100))